# Generated by Django 2.1.7 on 2019-09-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=32, verbose_name='待办事项')),
                ('status', models.SmallIntegerField(choices=[(1, '已完成'), (2, '未完成')], verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '待办清单',
                'verbose_name_plural': '待办清单',
                'db_table': 'things',
                'ordering': ['-update_time'],
            },
        ),
    ]
